### get all test
GET http://localhost:3000/projects

### get single test
GET http://localhost:3000/projects/65c701e969ff224d2827ff64

### Create New Project test
POST  http://localhost:3000/projects
Content-Type: application/json

{
    "name":"Test",
    "startDate":"NOT A DATE",
    "nextCheckIn":"NOT A DATE4",
    "projectedCompletionDate":"01/04/2024",
    "collabEnviornment":"test",
    "weeklyTimeRequirement":"4",
    "primaryDriver":"Ian Moes"
}

###
PUT http://localhost:3000/projects/65ced243dda20dca5c599b82 HTTP/1.1
Content-Type:application/json

{
    "name":"Project for Promotion",
    "startDate":"01/01/2024",
    "nextCheckIn":"01/03/2024",
    "projectedCompletionDate":"01/04/2024",
    "collabEnviornment":"This Project",
    "weeklyTimeRequirement":"12 Hours",
    "primaryDriver":"Ian Moes"
}

###
DELETE http://localhost:3000/projects/65cecf2ed872c3973b7a4eb0


# render links
###
GET https://cse-341-w05-w08.onrender.com/projects

### get single test
GET https://cse-341-w05-w08.onrender.com/projects/65c701e969ff224d2827ff63

### Create New Project test
POST  https://cse-341-w05-w08.onrender.com/projects
Content-Type: application/json

{
    "name":"Test",
    "startDate":"01/01/2024",
    "nextCheckIn":"03/05/2024",
    "projectedCompletionDate":"04/01/2024",
    "collabEnviornment":"test",
    "weeklyTimeRequirement":"4",
    "primaryDriver":"Ian Moes"
}

###
PUT https://cse-341-w05-w08.onrender.com/projects/65cee47314d4f90bc398bce5 HTTP/1.1
Content-Type:application/json

{
    "name":"Testing for PUT",
    "startDate":"02/19/2024",
    "nextCheckIn":"01/03/2024",
    "projectedCompletionDate":"01/04/2024",
    "collabEnviornment":"TBD",
    "weeklyTimeRequirement":"4",
    "primaryDriver":"Aditya Kalania"
}


###
DELETE https://cse-341-w05-w08.onrender.com/projects/65cee47314d4f90bc398bce5







### Create New contributor test
POST  https://cse-341-w05-w08.onrender.com/contributors
Content-Type: application/json

{
    "firstName":"Joshua",
    "lastName":"Moes",
    "email":"brother@cici.com"
   
}

### Delete newly created contributor
DELETE  https://cse-341-w05-w08.onrender.com/contributors/65c7028e69ff224d2827ff69



### get single test
GET https://cse-341-w05-w08.onrender.com/contributors/65e40a86bd4ba5247b14ef94

### update contributor test
PUT https://cse-341-w05-w08.onrender.com/contributors/65e40a86bd4ba5247b14ef94 HTTP/1.1
Content-Type:application/json

{
    "firstName":"Testing",
    "lastName":"Moes",
    "email":"moe20012@byui.edu"
   
}

### update contributor test (Change back
PUT https://cse-341-w05-w08.onrender.com/contributors/65e40a86bd4ba5247b14ef94 HTTP/1.1
Content-Type:application/json

{
    "firstName":"Ian Arthur",
    "lastName":"Moes",
    "email":"ian.moes94@gmail.com"
   
}